# Generated by Django 5.0.6 on 2024-07-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Patient',
            new_name='patient',
        ),
    ]
